### ISSUE TITLE
TypeError: Fetch argument None has invalid type <class 'NoneType'>

### ISSUE THREAD

**Issue by timelfrinkmob** [spring01/drlbox#1]
I am encountering this error when putting num_parallel to 1 when putting algorithm to 'dqn'.

`Traceback (most recent call last):
  File "Code/drlbox/examples/atari_dqn.py", line 93, in <module>
    trainer.run()
  File "Code/drlbox/drlbox/trainer/trainer_base.py", line 132, in run
    self.worker(0)
  File "Code/drlbox/drlbox/trainer/trainer_base.py", line 247, in worker
    self.train_on_env(env)
  File "Code/drlbox/drlbox/trainer/trainer_base.py", line 265, in train_on_env
    self.sync_to_global()
  File "Code/drlbox/drlbox/trainer/dqn_trainer.py", line 77, in sync_to_global
    self.online_net.sync()
  File "Code/drlbox/drlbox/net/net_base.py", line 86, in sync
    self.sess.run(self.op_sync)
  File "lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "lib/python3.5/site-packages/tensorflow/python/client/session.py", line 420, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "lib/python3.5/site-packages/tensorflow/python/client/session.py", line 237, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType'>`

**Comment by spring01** [comment]
Thanks for catching this bug! I made a temporary fix in commit 123ea41 and so it should work now. Will try to completely throw away distributed TensorFlow in the single process case.
